import { describe, expect, test } from "bun:test";
import { renderShellExportView } from "@/ui/shell/render.ts";

describe("renderShellExportView", () => {
  test("renders comments followed by quoted environment exports", () => {
    expect(
      renderShellExportView({
        env: { ALTERTABLE_PROFILE: "acme_prod" },
        comments: ["Generated by: altertable profile direnv"],
      }),
    ).toBe('# Generated by: altertable profile direnv\nexport ALTERTABLE_PROFILE="acme_prod"');
  });
});
