import { describe, expect, test } from "bun:test";
import { getOpenapiSpecYaml, stripOpenapiSourceHeader } from "@/lib/openapi-spec.ts";

describe("openapi-spec", () => {
  test("stripOpenapiSourceHeader removes bundled source comments", () => {
    const yaml = `# AUTO-GENERATED by example
# Edit source instead.
openapi: 3.1.0
info:
  title: Example
`;

    expect(stripOpenapiSourceHeader(yaml)).toBe(`openapi: 3.1.0
info:
  title: Example
`);
  });

  test("stripOpenapiSourceHeader leaves yaml without a source header unchanged", () => {
    const yaml = "openapi: 3.1.0\n";
    expect(stripOpenapiSourceHeader(yaml)).toBe(yaml);
  });

  test("getOpenapiSpecYaml omits AUTO-GENERATED header comments", () => {
    const yaml = getOpenapiSpecYaml();
    expect(yaml.startsWith("openapi: 3.1.0")).toBe(true);
    expect(yaml).not.toContain("AUTO-GENERATED");
  });
});
