import openapiTS, { astToString } from "openapi-typescript";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const specPath = join(import.meta.dir, "../openapi/openapi.yaml");
const outputPath = join(import.meta.dir, "../src/generated/openapi-types.ts");

const spec = readFileSync(specPath, "utf8");
const ast = await openapiTS(spec);
const types = astToString(ast);
writeFileSync(
  outputPath,
  `/* AUTO-GENERATED by scripts/generate-openapi-types.ts — do not edit */\n\n${types}\n`,
);
console.log(`Wrote ${outputPath}`);
