import openapiTS, { astToString } from "openapi-typescript";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  parseGeneratedArtifactMode,
  updateOrCheckGeneratedArtifact,
} from "@/../scripts/generated-artifact.ts";

const specPath = join(import.meta.dir, "../openapi/openapi.yaml");
const outputPath = join(import.meta.dir, "../src/generated/openapi-types.ts");

const spec = readFileSync(specPath, "utf8");
const ast = await openapiTS(spec);
const types = astToString(ast);
const mode = parseGeneratedArtifactMode(process.argv.slice(2));
updateOrCheckGeneratedArtifact({
  outputPath,
  content: `/* AUTO-GENERATED by scripts/generate-openapi-types.ts — do not edit */\n\n${types}\n`,
  mode,
});
console.log(`${mode === "check" ? "Checked" : "Wrote"} ${outputPath}`);
