import { readFileSync } from "node:fs";
import { join } from "node:path";
import { generatedArtifactMode, syncGeneratedArtifact } from "@/../scripts/generated-artifact.ts";

const HTTP_METHODS = ["get", "post", "patch", "delete", "put"] as const;

type OpenapiDocument = {
  paths?: Record<
    string,
    Partial<Record<(typeof HTTP_METHODS)[number], { operationId?: string; summary?: string }>>
  >;
};

const specPath = join(import.meta.dir, "../openapi/openapi.yaml");
const outputPath = join(import.meta.dir, "../src/generated/openapi-operations.ts");

const specText = readFileSync(specPath, "utf8");
const document = Bun.YAML.parse(specText) as OpenapiDocument;

type OpenapiOperationEntry = {
  operationId: string;
  method: string;
  path: string;
  summary: string;
};

const operations: OpenapiOperationEntry[] = [];

for (const [path, pathItem] of Object.entries(document.paths ?? {})) {
  if (!pathItem) {
    continue;
  }
  for (const method of HTTP_METHODS) {
    const operation = pathItem[method];
    if (!operation?.operationId) {
      continue;
    }
    operations.push({
      operationId: operation.operationId,
      method: method.toUpperCase(),
      path,
      summary: operation.summary ?? "",
    });
  }
}

operations.sort((left, right) => {
  const pathCompare = left.path.localeCompare(right.path);
  if (pathCompare !== 0) {
    return pathCompare;
  }
  return left.method.localeCompare(right.method);
});

const lines = operations.map(
  (operation) =>
    `  { operationId: ${JSON.stringify(operation.operationId)}, method: ${JSON.stringify(operation.method)}, path: ${JSON.stringify(operation.path)}, summary: ${JSON.stringify(operation.summary)} },`,
);

const output = `/* AUTO-GENERATED by scripts/generate-openapi-index.ts — do not edit */

export type OpenapiOperation = {
  operationId: string;
  method: string;
  path: string;
  summary: string;
};

export const OPENAPI_OPERATIONS: OpenapiOperation[] = [
${lines.join("\n")}
];
`;

const mode = generatedArtifactMode(process.argv.slice(2));
syncGeneratedArtifact({ outputPath, content: output, mode });
console.log(
  `${mode === "check" ? "Checked" : "Wrote"} ${outputPath} (${operations.length} operations)`,
);
